sudo: required
dist: trusty
services:
  - docker
language: python
python:
  - "3.5"
install:
  - pip install click pycodestyle
script:
  - python3 ./scripts/run_tests.py --build-docker-images --docker --verbose
  - python3 ./scripts/check_code_style.py
