sudo: required
dist: trusty
language: python
python:
  - "3.5"
  - "3.6"
install:
  - sudo apt-get -y install snapd
  - pip install click ruamel.yaml schema progressbar2
script:
  - python3 ./tests/run_tests.py --perform-on-host
